/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceScoutingGameRouteImport } from './routes/workspace.scouting-game'
import { Route as WorkspaceQaAssistanceRouteImport } from './routes/workspace.qa-assistance'
import { Route as WorkspacePredictionsRouteImport } from './routes/workspace.predictions'
import { Route as WorkspaceOverviewRouteImport } from './routes/workspace.overview'
import { Route as WorkspaceGroupWorkflowRouteImport } from './routes/workspace.group-workflow'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/workspace.analytics'
import { Route as OpsMlflowRouteImport } from './routes/ops.mlflow'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceScoutingGameRoute = WorkspaceScoutingGameRouteImport.update({
  id: '/scouting-game',
  path: '/scouting-game',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceQaAssistanceRoute = WorkspaceQaAssistanceRouteImport.update({
  id: '/qa-assistance',
  path: '/qa-assistance',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePredictionsRoute = WorkspacePredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceGroupWorkflowRoute = WorkspaceGroupWorkflowRouteImport.update({
  id: '/group-workflow',
  path: '/group-workflow',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OpsMlflowRoute = OpsMlflowRouteImport.update({
  id: '/ops/mlflow',
  path: '/ops/mlflow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/ops/mlflow': typeof OpsMlflowRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/group-workflow': typeof WorkspaceGroupWorkflowRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/predictions': typeof WorkspacePredictionsRoute
  '/workspace/qa-assistance': typeof WorkspaceQaAssistanceRoute
  '/workspace/scouting-game': typeof WorkspaceScoutingGameRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ops/mlflow': typeof OpsMlflowRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/group-workflow': typeof WorkspaceGroupWorkflowRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/predictions': typeof WorkspacePredictionsRoute
  '/workspace/qa-assistance': typeof WorkspaceQaAssistanceRoute
  '/workspace/scouting-game': typeof WorkspaceScoutingGameRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/ops/mlflow': typeof OpsMlflowRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/group-workflow': typeof WorkspaceGroupWorkflowRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/predictions': typeof WorkspacePredictionsRoute
  '/workspace/qa-assistance': typeof WorkspaceQaAssistanceRoute
  '/workspace/scouting-game': typeof WorkspaceScoutingGameRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/ops/mlflow'
    | '/workspace/analytics'
    | '/workspace/group-workflow'
    | '/workspace/overview'
    | '/workspace/predictions'
    | '/workspace/qa-assistance'
    | '/workspace/scouting-game'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ops/mlflow'
    | '/workspace/analytics'
    | '/workspace/group-workflow'
    | '/workspace/overview'
    | '/workspace/predictions'
    | '/workspace/qa-assistance'
    | '/workspace/scouting-game'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/ops/mlflow'
    | '/workspace/analytics'
    | '/workspace/group-workflow'
    | '/workspace/overview'
    | '/workspace/predictions'
    | '/workspace/qa-assistance'
    | '/workspace/scouting-game'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  OpsMlflowRoute: typeof OpsMlflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/scouting-game': {
      id: '/workspace/scouting-game'
      path: '/scouting-game'
      fullPath: '/workspace/scouting-game'
      preLoaderRoute: typeof WorkspaceScoutingGameRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/qa-assistance': {
      id: '/workspace/qa-assistance'
      path: '/qa-assistance'
      fullPath: '/workspace/qa-assistance'
      preLoaderRoute: typeof WorkspaceQaAssistanceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/predictions': {
      id: '/workspace/predictions'
      path: '/predictions'
      fullPath: '/workspace/predictions'
      preLoaderRoute: typeof WorkspacePredictionsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/overview': {
      id: '/workspace/overview'
      path: '/overview'
      fullPath: '/workspace/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/group-workflow': {
      id: '/workspace/group-workflow'
      path: '/group-workflow'
      fullPath: '/workspace/group-workflow'
      preLoaderRoute: typeof WorkspaceGroupWorkflowRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/analytics': {
      id: '/workspace/analytics'
      path: '/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/ops/mlflow': {
      id: '/ops/mlflow'
      path: '/ops/mlflow'
      fullPath: '/ops/mlflow'
      preLoaderRoute: typeof OpsMlflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceGroupWorkflowRoute: typeof WorkspaceGroupWorkflowRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspacePredictionsRoute: typeof WorkspacePredictionsRoute
  WorkspaceQaAssistanceRoute: typeof WorkspaceQaAssistanceRoute
  WorkspaceScoutingGameRoute: typeof WorkspaceScoutingGameRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceGroupWorkflowRoute: WorkspaceGroupWorkflowRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspacePredictionsRoute: WorkspacePredictionsRoute,
  WorkspaceQaAssistanceRoute: WorkspaceQaAssistanceRoute,
  WorkspaceScoutingGameRoute: WorkspaceScoutingGameRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  OpsMlflowRoute: OpsMlflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
